#!/bin/bash
# converge xml of environment and structure. 
unitPath=$1

if [[ "$unitPath" == "" ]]
then
	path=$(pwd)
	if [[ -d ${path} ]]; then
		cd ${AutoLatex_HOME}/components/
		java com/takamagahara/converger/ConvergerEntry $path
		# show result
		tree -c $path/Target
	else
		echoc.sh "Wrong Path, check your input. The parameter should be the absolute path of the project. " red subline
	fi
else
	if [[ "$unitPath" == "--help" ]]; then
		echoc.sh "converger to converge environment and structure xml. " green subline
	else
		path=$(pwd)
		if [[ -d ${path} ]]; then
			cd ${AutoLatex_HOME}/components/
			java com/takamagahara/converger/ConvergerEntry $path $unitPath
			# show result
			tree -c $path/Target
		else
			echoc.sh "Wrong Path, check your input. The parameter should be the absolute path of the project. " red subline
		fi
	fi
fi