#!/bin/bash
# converge xml of environment and structure. 
helpOrNot=$1

if [[ "$helpOrNot" == "" ]]
then
	path=$(pwd)
	if [[ -d ${path} ]]; then
		cd ${AutoLatex_HOME}/components/
		java com/takamagahara/converger/ConvergerEntry $path
		# show result
		tree -c $path/Target
	else
		echoc.sh "Wrong Path, check your input. The parameter should be the absolute path of the project. " red subline
	fi
else
	if [[ "$helpOrNot" == "--help" ]]; then
		echoc.sh "converger to converge environment and structure xml. " green subline
	else
		echoc.sh "Unrecognized parameter "${helpOrNot}" using --help for help. " red flash
	fi
fi